application: freshman
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: hello.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest